export type BroadcastStyle =
  | "champions_league"
  | "fifa"
  | "retro"
  | "espn"
  | "street"
  | "data_geek"
  | "gazette"
  | "social"
  | "copa_mundo"
  | "netflix"
  | "world_cup"
  | "world_cup_mexico"
  | "world_cup_canada"
  | "world_cup_usa"
  | "retro_football"
  | "copa_mundo_bc"
  | "european_nights";


export const BROADCAST_STYLES: Record<BroadcastStyle, { name: string; description: string; preview: string }> = {
  champions_league: { name: "Champions League", description: "Elitaire donkerblauwe premium stijl met gouden accenten", preview: "⭐" },
  fifa: { name: "FIFA / EA Sports", description: "Game-HUD met neon groene gradients en futuristische UI", preview: "🎮" },
  retro: { name: "Retro Scorebord", description: "Nostalgisch amber terminal met flip-scorebord gevoel", preview: "🏟️" },
  espn: { name: "Breaking News", description: "Urgente rode ticker-stijl zoals Sky Sports & ESPN", preview: "📺" },
  street: { name: "Street Football", description: "Stedelijke graffiti-stijl met neon op beton", preview: "🏀" },
  data_geek: { name: "Data Geek", description: "Analytisch dashboard met matrix-achtige data visualisatie", preview: "📊" },
  gazette: { name: "La Gazzetta", description: "Iconische roze Italiaanse sportkrant met serif headers", preview: "📰" },
  social: { name: "Social Feed", description: "Instagram-achtig met afgeronde cards en zachte gradients", preview: "📱" },
  copa_mundo: { name: "Copa Mundo", description: "Premium Europees avondvoetbal: diep marineblauw met elektrisch blauw, Montserrat typografie", preview: "🏆" },
  netflix: { name: "Netflix", description: "Cinematisch zwart met iconisch rood en filmische spanning", preview: "🎬" },
  world_cup: { name: "World Cup 2026", description: "Koraal-roze met zwarte capsule-cards, gele cirkel accenten en vette typografie", preview: "🌎" },
  world_cup_mexico: { name: "World Cup — Mexico", description: "Groene host-nation stijl met chevron print zoals op de Trionda bal", preview: "🇲🇽" },
  world_cup_canada: { name: "World Cup — Canada", description: "Rode host-nation stijl met chevron print zoals op de Trionda bal", preview: "🇨🇦" },
  world_cup_usa: { name: "World Cup — USA", description: "Blauwe host-nation stijl met sterren print zoals op de Trionda bal", preview: "🇺🇸" },
  copa_mundo_bc: { name: "Copa Mundo", description: "Broadcast Style #1 — de native Copa Mundo identiteit: donkergroen/zwart met geel (dark) en diep blauw (light), Inter typografie", preview: "🟡" },
  retro_football: { name: "Retro Football", description: "Vintage matchdayprogramma uit de jaren '70/'80: crèmepapier, bosgroen en verschoten rood met Roboto Condensed", preview: "📕" },
  european_nights: { name: "European Nights", description: "Broadcast Style #2 — premium Europese voetbalavond: middernachtblauw met elektrisch blauw en violet accent, Barlow Condensed + Inter", preview: "🌙" },
};


const STYLES: Record<BroadcastStyle, Record<string, string>> = {
  // ── 1. CHAMPIONS LEAGUE ───
  champions_league: {
    sectionDot: "h-2 w-2 rounded-full bg-accent shadow-[0_0_6px_hsl(var(--accent))]",
    sectionTitle: "text-base font-black text-primary uppercase tracking-[0.18em]",
    sectionLine: "flex-1 h-px bg-gradient-to-r from-accent/40 via-accent/15 to-transparent",
    cardHeader: "bg-accent text-accent-foreground border-b border-accent px-3 py-2 flex items-center gap-2 shadow-[0_0_8px_-2px_hsl(var(--accent)/0.4)]",
    cardHeaderDot: "h-1.5 w-1.5 rounded-full bg-accent-foreground shadow-[0_0_4px_hsl(var(--accent-foreground)/0.6)]",
    cardHeaderTitle: "text-[10px] font-bold text-accent-foreground uppercase tracking-[0.12em]",
    card: "rounded-lg border border-primary/20 bg-card overflow-hidden shadow-[0_0_16px_-6px_hsl(var(--primary)/0.1)]",
    tabActive: "flex-1 px-2.5 py-1.5 rounded-md text-[10px] font-bold uppercase tracking-[0.1em] transition-all bg-primary text-primary-foreground shadow-sm",
    tabInactive: "flex-1 px-2.5 py-1.5 rounded-md text-[10px] font-medium uppercase tracking-wider transition-all text-muted-foreground hover:text-accent hover:bg-accent/5",
    tabContainer: "flex rounded-lg bg-card border border-primary/15 p-0.5 gap-0.5 shadow-inner",
    badge: "inline-flex items-center rounded-full bg-accent/12 border border-accent/25 px-2 py-0.5 text-[9px] font-bold text-accent tabular-nums",
    label: "text-[8px] font-bold uppercase tracking-[0.18em] text-accent",
    backButton: "flex items-center gap-1 text-[11px] text-accent font-bold uppercase tracking-[0.12em]",
    matchContext: "bg-accent/10 px-3 py-1 border-b border-accent/20",
    matchContextText: "text-[8px] font-bold uppercase tracking-[0.15em] text-accent",
    matchTeamRowWin: "bg-primary/8",
    matchTeamName: "text-[11px] font-semibold truncate",
    matchTeamNameFav: "text-accent",
    matchScore: "text-sm font-bold tabular-nums",
    matchScoreWin: "text-primary",
    matchScoreLose: "text-muted-foreground",
    matchTimeBadge: "inline-flex items-center rounded-full bg-primary/12 border border-primary/20 px-2.5 py-0.5 text-[9px] font-bold text-primary tabular-nums",
    matchFooter: "flex items-center justify-between px-3 py-1 bg-accent/[0.04] border-t border-accent/12",
    navBar: "bg-card/98 backdrop-blur-xl border-t border-primary/20 shadow-[0_-2px_16px_-4px_hsl(var(--primary)/0.08)]",
    navCenter: "bg-primary text-primary-foreground border-primary/40 shadow-sm rounded-xl",
    navCenterActive: "bg-primary text-primary-foreground border-primary scale-105 shadow-md rounded-xl",
    navTab: "text-muted-foreground hover:text-accent",
    navTabActive: "text-accent",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-4 h-0.5 rounded-full bg-accent",
    tableHeader: "bg-accent/8 text-[9px] font-bold uppercase tracking-[0.1em] text-accent/70 border-b border-accent/15",
    tableRowAlt: "bg-primary/[0.03]",
    ptsBadge: "inline-flex items-center justify-center rounded-full bg-primary/15 border border-primary/25 px-1.5 py-0.5 text-[11px] font-bold text-primary",
    timeslotHeader: "bg-primary text-primary-foreground flex items-center gap-2 px-3 py-1.5 border-b border-primary",
    dateHeader: "bg-accent text-accent-foreground px-2.5 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-[0.12em]",
    phaseTab: "px-2.5 py-1 rounded-md text-[9px] font-bold uppercase tracking-[0.1em] whitespace-nowrap transition-all",
    phaseTabActive: "bg-accent text-accent-foreground shadow-sm",
    phaseTabInactive: "bg-card border border-primary/15 text-muted-foreground hover:text-accent hover:border-accent/25",
    subHeader: "px-3 py-2 flex items-center justify-between gap-2 bg-primary/5 border-l-2 border-l-primary/50",
    subHeaderTitle: "text-[10px] font-black uppercase tracking-[0.12em] text-foreground",
    subLabel: "inline-flex items-center px-2 py-0.5 text-[9px] font-bold uppercase tracking-[0.1em] text-muted-foreground",
  },

  // ── 2. FIFA / EA SPORTS ───
  fifa: {
    sectionDot: "h-1.5 w-4 bg-accent clip-path-[polygon(0_0,100%_0,85%_100%,0_100%)]",
    sectionTitle: "text-base font-black text-foreground uppercase tracking-[0.12em] italic",
    sectionLine: "flex-1 h-[1.5px] bg-gradient-to-r from-primary/50 via-accent/25 to-transparent",
    cardHeader: "bg-gradient-to-r from-primary to-accent/80 text-primary-foreground border-b border-primary px-3 py-2 flex items-center gap-2 -skew-x-1",
    cardHeaderDot: "h-2.5 w-0.5 bg-primary-foreground rounded-sm",
    cardHeaderTitle: "text-[10px] font-bold text-primary-foreground uppercase tracking-[0.12em] italic skew-x-1",
    card: "rounded-md border border-primary/20 bg-card overflow-hidden shadow-sm relative before:absolute before:inset-0 before:bg-gradient-to-br before:from-primary/[0.02] before:to-transparent before:pointer-events-none",
    tabActive: "flex-1 px-2.5 py-1.5 text-[10px] font-bold uppercase tracking-[0.1em] italic transition-all bg-gradient-to-r from-primary to-accent/80 text-primary-foreground shadow-sm -skew-x-2",
    tabInactive: "flex-1 px-2.5 py-1.5 text-[10px] font-medium uppercase italic tracking-wider transition-all text-muted-foreground hover:text-foreground -skew-x-2",
    tabContainer: "flex bg-card border border-primary/15 p-0.5 gap-0.5 rounded-md",
    badge: "inline-flex items-center bg-primary/15 border-l-2 border-primary px-2 py-0.5 text-[9px] font-bold text-primary italic tabular-nums -skew-x-2",
    label: "text-[8px] font-bold uppercase tracking-[0.18em] text-accent italic",
    backButton: "flex items-center gap-1 text-[11px] text-primary font-bold uppercase tracking-[0.12em] italic",
    matchContext: "bg-gradient-to-r from-accent/15 via-accent/5 to-transparent px-3 py-1 border-l-2 border-accent",
    matchContextText: "text-[8px] font-bold uppercase tracking-[0.15em] text-accent italic",
    matchTeamRowWin: "bg-gradient-to-r from-primary/8 to-transparent",
    matchTeamName: "text-[11px] font-semibold truncate italic",
    matchTeamNameFav: "text-primary",
    matchScore: "text-base font-bold tabular-nums italic",
    matchScoreWin: "text-primary",
    matchScoreLose: "text-muted-foreground/50",
    matchTimeBadge: "inline-flex items-center bg-accent/15 border border-accent/25 px-2.5 py-0.5 text-[9px] font-bold text-accent italic tabular-nums -skew-x-3",
    matchFooter: "flex items-center justify-between px-3 py-1 bg-primary/4 border-t border-primary/15",
    navBar: "bg-card/95 backdrop-blur-xl border-t border-primary/25 shadow-[0_-2px_16px_-4px_hsl(var(--primary)/0.1)]",
    navCenter: "bg-gradient-to-br from-primary to-accent/60 text-primary-foreground border-primary/40 -skew-x-3 rounded-lg",
    navCenterActive: "bg-gradient-to-br from-primary to-accent/60 text-primary-foreground border-primary scale-105 shadow-md -skew-x-3 rounded-lg",
    navTab: "text-muted-foreground hover:text-foreground",
    navTabActive: "text-primary",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-5 h-[1.5px] bg-gradient-to-r from-primary to-accent -skew-x-6",
    tableHeader: "bg-gradient-to-r from-accent/10 to-transparent text-[9px] font-bold uppercase tracking-[0.1em] italic text-accent/70 border-b border-accent/20",
    tableRowAlt: "bg-primary/[0.02]",
    ptsBadge: "inline-flex items-center justify-center bg-gradient-to-r from-primary/20 to-accent/12 border border-primary/25 px-1.5 py-0.5 text-[11px] font-bold text-primary italic -skew-x-2",
    timeslotHeader: "bg-gradient-to-r from-primary to-accent/70 text-primary-foreground flex items-center gap-2 px-3 py-1.5 border-b border-primary -skew-x-1",
    dateHeader: "bg-gradient-to-r from-primary to-accent/70 text-primary-foreground px-3 py-0.5 text-[9px] font-bold uppercase tracking-[0.12em] italic -skew-x-3",
    phaseTab: "px-2.5 py-1 text-[9px] font-bold uppercase tracking-[0.1em] italic whitespace-nowrap transition-all -skew-x-2",
    phaseTabActive: "bg-gradient-to-r from-primary to-accent/70 text-primary-foreground shadow-sm",
    phaseTabInactive: "bg-card border border-primary/15 text-muted-foreground hover:text-foreground hover:bg-primary/4",
    subHeader: "px-3 py-2 flex items-center justify-between gap-2 bg-primary/8 border-l-2 border-l-primary -skew-x-1",
    subHeaderTitle: "text-[10px] font-black uppercase tracking-[0.12em] italic text-foreground skew-x-1",
    subLabel: "inline-flex items-center px-2 py-0.5 text-[9px] font-bold italic uppercase tracking-[0.1em] text-accent",
  },

  // ── 3. RETRO SCOREBORD ───
  retro: {
    sectionDot: "h-1.5 w-1.5 bg-primary",
    sectionTitle: "font-mono text-sm font-bold text-foreground uppercase tracking-[0.2em]",
    sectionLine: "flex-1 border-b border-dotted border-primary/25",
    cardHeader: "bg-primary text-primary-foreground border-b-2 border-primary px-3 py-2 flex items-center gap-2",
    cardHeaderDot: "h-1.5 w-1.5 bg-primary-foreground",
    cardHeaderTitle: "font-mono text-[10px] font-bold text-primary-foreground uppercase tracking-[0.15em]",
    card: "border border-primary/20 bg-card overflow-hidden",
    tabActive: "flex-1 px-2.5 py-1.5 text-[10px] font-mono font-bold uppercase tracking-[0.12em] transition-all bg-primary text-primary-foreground",
    tabInactive: "flex-1 px-2.5 py-1.5 text-[10px] font-mono font-medium uppercase tracking-[0.12em] transition-all text-muted-foreground hover:text-foreground hover:bg-primary/8",
    tabContainer: "flex bg-card border border-primary/20 p-0.5 gap-0.5",
    badge: "inline-flex items-center border border-primary/30 bg-primary/8 px-2 py-0.5 text-[9px] font-mono font-bold text-primary tabular-nums",
    label: "text-[9px] font-mono font-bold uppercase tracking-[0.18em] text-primary",
    backButton: "flex items-center gap-1 text-[11px] font-mono font-bold text-primary uppercase tracking-[0.12em]",
    matchContext: "bg-primary/8 px-3 py-1 border-b border-dotted border-primary/15",
    matchContextText: "text-[9px] font-mono font-bold uppercase tracking-[0.12em] text-primary",
    matchTeamRow: "rounded-none",
    matchTeamRowWin: "bg-primary/8",
    matchTeamName: "text-[11px] font-mono font-semibold truncate uppercase",
    matchTeamNameFav: "text-primary",
    matchScore: "text-lg font-mono font-bold tabular-nums tracking-wider",
    matchScoreWin: "text-primary",
    matchScoreLose: "text-muted-foreground",
    matchTimeBadge: "inline-flex items-center border border-primary/25 bg-primary/8 px-2.5 py-0.5 text-[10px] font-mono font-bold text-primary tabular-nums tracking-widest",
    matchFooter: "flex items-center justify-between px-3 py-1 bg-primary/4 border-t border-dotted border-primary/15",
    navBar: "bg-card border-t border-primary/25",
    navCenter: "bg-primary text-primary-foreground border-primary rounded-none",
    navCenterActive: "bg-primary text-primary-foreground border-primary rounded-none scale-105",
    navTab: "text-muted-foreground hover:text-foreground font-mono",
    navTabActive: "text-primary font-mono",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-4 h-0.5 bg-primary",
    tableHeader: "bg-primary/8 text-[9px] font-mono font-bold uppercase tracking-[0.12em] text-primary border-b border-primary/20",
    tableRowAlt: "bg-primary/[0.03]",
    ptsBadge: "inline-flex items-center justify-center border border-primary/25 bg-primary/12 px-1.5 py-0.5 text-[11px] font-mono font-bold text-primary tabular-nums",
    timeslotHeader: "bg-primary text-primary-foreground flex items-center gap-2 px-3 py-1.5 border-b-2 border-dotted border-primary",
    timeslotBadge: "inline-flex items-center border border-primary-foreground/40 bg-primary-foreground/10 px-2 py-0.5 text-[9px] font-mono font-bold text-primary-foreground tabular-nums",
    timeslotHeaderMeta: "text-[10px] font-mono font-bold text-primary-foreground/80 uppercase tracking-wider",
    dateHeader: "bg-primary text-primary-foreground px-2.5 py-0.5 text-[9px] font-mono font-bold uppercase tracking-[0.15em]",
    matchCardWrapper: "border border-border/60 bg-card overflow-hidden shadow-sm",
    phaseTab: "px-2.5 py-1 text-[9px] font-mono font-bold uppercase tracking-[0.12em] whitespace-nowrap transition-all",
    phaseTabActive: "bg-primary text-primary-foreground",
    phaseTabInactive: "bg-card border border-primary/20 text-muted-foreground hover:text-foreground hover:bg-primary/8",
    subHeader: "px-3 py-2 flex items-center justify-between gap-2 bg-primary/8 border-l-2 border-l-primary",
    subHeaderTitle: "font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-foreground",
    subLabel: "inline-flex items-center px-2 py-0.5 font-mono text-[9px] font-bold uppercase tracking-[0.12em] text-primary",
  },

  // ── 4. BREAKING NEWS / ESPN ───
  espn: {
    sectionDot: "h-2.5 w-0.5 bg-primary rounded-sm",
    sectionTitle: "text-base font-black text-foreground uppercase tracking-wide",
    sectionLine: "flex-1 h-[1.5px] bg-accent/35",
    cardHeader: "bg-accent text-accent-foreground px-3 py-2 flex items-center gap-2",
    cardHeaderDot: "h-1 w-1 rounded-full bg-accent-foreground animate-pulse",
    cardHeaderTitle: "text-[10px] font-bold text-accent-foreground uppercase tracking-wider",
    card: "rounded-none border-l-3 border-primary bg-card overflow-hidden shadow-sm",
    tabActive: "flex-1 px-2.5 py-1.5 text-[10px] font-bold uppercase tracking-wider transition-all bg-primary text-primary-foreground",
    tabInactive: "flex-1 px-2.5 py-1.5 text-[10px] font-bold uppercase tracking-wider transition-all text-muted-foreground hover:text-foreground hover:bg-secondary",
    tabContainer: "flex bg-secondary p-0.5 gap-0.5",
    badge: "inline-flex items-center bg-primary text-primary-foreground px-2 py-0.5 text-[9px] font-bold uppercase tabular-nums",
    label: "text-[8px] font-bold uppercase tracking-[0.12em] text-primary",
    backButton: "flex items-center gap-1 text-[11px] text-primary font-bold uppercase tracking-wider",
    matchContext: "bg-accent text-accent-foreground px-3 py-1",
    matchContextText: "text-[8px] font-bold uppercase tracking-[0.12em] text-accent-foreground",
    matchTeamRowWin: "bg-primary/8 border-l-2 border-primary",
    matchTeamName: "text-[11px] font-bold truncate uppercase",
    matchTeamNameFav: "text-primary",
    matchScore: "text-base font-bold tabular-nums",
    matchScoreWin: "text-primary",
    matchScoreLose: "text-muted-foreground",
    matchTimeBadge: "inline-flex items-center bg-primary text-primary-foreground px-2.5 py-0.5 text-[9px] font-bold tabular-nums uppercase",
    matchFooter: "flex items-center justify-between px-3 py-1 bg-accent/8 border-t border-accent/20",
    navBar: "bg-card border-t-3 border-primary",
    navCenter: "bg-primary text-primary-foreground border-primary rounded-none",
    navCenterActive: "bg-primary text-primary-foreground border-primary scale-105 shadow-md rounded-none",
    navTab: "text-muted-foreground hover:text-foreground",
    navTabActive: "text-primary",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-5 h-0.5 bg-primary",
    tableHeader: "bg-accent text-accent-foreground text-[9px] font-bold uppercase tracking-wider",
    tableRowAlt: "bg-accent/[0.04]",
    ptsBadge: "inline-flex items-center justify-center bg-primary text-primary-foreground px-1.5 py-0.5 text-[11px] font-bold",
    timeslotHeader: "bg-accent/8 flex items-center gap-2 px-3 py-1.5 border-b border-accent/20",
    dateHeader: "bg-accent text-accent-foreground px-3 py-0.5 text-[9px] font-bold uppercase tracking-wider",
    phaseTab: "px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider whitespace-nowrap transition-all",
    phaseTabActive: "bg-primary text-primary-foreground",
    phaseTabInactive: "bg-accent/8 border border-accent/20 text-muted-foreground hover:text-foreground hover:bg-accent/12",
    subHeader: "px-3 py-2 flex items-center justify-between gap-2 bg-secondary border-l-3 border-l-primary",
    subHeaderTitle: "text-[10px] font-bold uppercase tracking-wider text-foreground",
    subLabel: "inline-flex items-center px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider text-primary",
  },

  // ── 5. STREET FOOTBALL ───
  street: {
    sectionDot: "h-2.5 w-2.5 bg-accent rotate-45",
    sectionTitle: "text-base font-black text-foreground uppercase tracking-tight -skew-x-3",
    sectionLine: "flex-1 h-1 bg-accent/20 -skew-x-6",
    cardHeader: "bg-accent text-accent-foreground border-b-3 border-accent px-3 py-2 flex items-center gap-2",
    cardHeaderDot: "h-2.5 w-2.5 bg-accent-foreground rotate-45",
    cardHeaderTitle: "text-[10px] font-bold text-accent-foreground uppercase tracking-tight -skew-x-2",
    card: "border border-foreground/15 bg-card overflow-hidden shadow-[4px_4px_0_hsl(var(--primary)/0.15)]",
    tabActive: "flex-1 px-2.5 py-1.5 text-[10px] font-bold uppercase tracking-tight transition-all bg-primary text-primary-foreground -skew-x-3 shadow-[3px_3px_0_hsl(var(--accent)/0.2)]",
    tabInactive: "flex-1 px-2.5 py-1.5 text-[10px] font-bold uppercase tracking-tight transition-all text-muted-foreground hover:text-foreground -skew-x-3",
    tabContainer: "flex bg-secondary/30 p-0.5 gap-0.5",
    badge: "inline-flex items-center bg-accent text-accent-foreground border-none px-2 py-0.5 text-[9px] font-bold tabular-nums uppercase -skew-x-6 shadow-[2px_2px_0_hsl(var(--foreground)/0.1)]",
    label: "text-[8px] font-bold uppercase tracking-tight text-accent -skew-x-2",
    backButton: "flex items-center gap-1 text-[11px] text-accent font-bold uppercase tracking-tight",
    matchContext: "bg-accent/12 border-l-3 border-accent px-3 py-1",
    matchContextText: "text-[8px] font-bold uppercase tracking-tight text-accent -skew-x-2",
    matchTeamRowWin: "bg-primary/8 border-l-2 border-primary",
    matchTeamName: "text-[11px] font-bold truncate uppercase",
    matchTeamNameFav: "text-accent",
    matchScore: "text-xl font-black tabular-nums",
    matchScoreWin: "text-primary",
    matchScoreLose: "text-muted-foreground",
    matchTimeBadge: "inline-flex items-center bg-foreground text-background px-3 py-0.5 text-[9px] font-bold tabular-nums uppercase -skew-x-6",
    matchFooter: "flex items-center justify-between px-3 py-1 bg-primary/4 border-t border-primary/12",
    navBar: "bg-card border-t-3 border-accent",
    navCenter: "bg-accent text-accent-foreground border-accent shadow-[3px_3px_0_hsl(var(--primary)/0.2)] rounded-none -skew-x-6",
    navCenterActive: "bg-accent text-accent-foreground border-accent scale-105 shadow-[4px_4px_0_hsl(var(--primary)/0.3)] rounded-none -skew-x-6",
    navTab: "text-muted-foreground hover:text-foreground",
    navTabActive: "text-accent",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-5 h-1 bg-accent -skew-x-12",
    tableHeader: "bg-accent/8 text-[9px] font-bold uppercase tracking-tight text-accent/70 border-b border-accent/15",
    tableRowAlt: "bg-foreground/[0.02]",
    ptsBadge: "inline-flex items-center justify-center bg-primary text-primary-foreground px-1.5 py-0.5 text-[11px] font-bold -skew-x-6",
    timeslotHeader: "bg-primary text-primary-foreground flex items-center gap-2 px-3 py-1.5 border-b border-primary -skew-x-3",
    dateHeader: "bg-accent text-accent-foreground px-3 py-0.5 text-[9px] font-bold uppercase tracking-tight -skew-x-6",
    phaseTab: "px-2.5 py-1 text-[9px] font-bold uppercase tracking-tight whitespace-nowrap transition-all -skew-x-3",
    phaseTabActive: "bg-accent text-accent-foreground shadow-[2px_2px_0_hsl(var(--primary)/0.15)]",
    phaseTabInactive: "bg-card border border-foreground/12 text-muted-foreground hover:text-foreground hover:bg-accent/8",
    subHeader: "px-3 py-2 flex items-center justify-between gap-2 bg-accent/12 border-l-3 border-l-accent -skew-x-3",
    subHeaderTitle: "text-[10px] font-black uppercase tracking-tight text-foreground skew-x-3",
    subLabel: "inline-flex items-center px-2 py-0.5 text-[9px] font-bold uppercase tracking-tight text-accent -skew-x-2",
  },

  // ── 6. DATA GEEK ───
  data_geek: {
    sectionDot: "h-1 w-1 rounded-full bg-accent shadow-[0_0_3px_hsl(var(--accent))]",
    sectionTitle: "font-mono text-xs font-bold text-primary uppercase tracking-[0.2em]",
    sectionLine: "flex-1 h-px border-t border-dashed border-primary/25",
    cardHeader: "bg-primary text-primary-foreground border-b border-primary px-3 py-1.5 flex items-center gap-2",
    cardHeaderDot: "h-1 w-1 rounded-full bg-accent shadow-[0_0_3px_hsl(var(--accent))]",
    cardHeaderTitle: "font-mono text-[9px] font-bold text-primary-foreground uppercase tracking-[0.15em]",
    card: "rounded-sm border border-primary/15 bg-card overflow-hidden",
    tabActive: "flex-1 px-2.5 py-1.5 rounded-sm text-[9px] font-mono font-bold uppercase tracking-[0.1em] transition-all bg-primary text-primary-foreground",
    tabInactive: "flex-1 px-2.5 py-1.5 rounded-sm text-[9px] font-mono font-medium uppercase tracking-[0.1em] transition-all text-muted-foreground hover:text-primary hover:bg-primary/4",
    tabContainer: "flex rounded-sm bg-card border border-primary/12 p-0.5 gap-0.5",
    badge: "inline-flex items-center rounded-sm border border-accent/25 bg-accent/8 px-1.5 py-0.5 text-[9px] font-mono font-bold text-accent tabular-nums",
    label: "text-[8px] font-mono font-bold uppercase tracking-[0.2em] text-accent",
    backButton: "flex items-center gap-1 text-[11px] font-mono font-bold text-primary uppercase tracking-[0.1em]",
    matchContext: "bg-accent/6 px-3 py-1 border-b border-dashed border-accent/12",
    matchContextText: "text-[8px] font-mono font-bold uppercase tracking-[0.12em] text-accent",
    matchTeamRowWin: "bg-accent/6",
    matchTeamName: "text-[11px] font-mono font-medium truncate",
    matchTeamNameFav: "text-primary font-semibold",
    matchScore: "text-xs font-mono font-bold tabular-nums",
    matchScoreWin: "text-accent",
    matchScoreLose: "text-muted-foreground",
    matchTimeBadge: "inline-flex items-center rounded-sm border border-primary/15 bg-primary/6 px-2.5 py-0.5 text-[9px] font-mono font-bold text-primary tabular-nums",
    matchFooter: "flex items-center justify-between px-3 py-1 border-t border-dashed border-primary/12",
    navBar: "bg-card border-t border-primary/15",
    navCenter: "bg-primary text-primary-foreground border-primary/25 rounded-sm",
    navCenterActive: "bg-primary text-primary-foreground border-primary rounded-sm scale-105",
    navTab: "text-muted-foreground hover:text-primary font-mono",
    navTabActive: "text-accent font-mono",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-3.5 h-0.5 bg-accent rounded-sm",
    tableHeader: "bg-primary/6 text-[8px] font-mono font-bold uppercase tracking-[0.15em] text-primary/55 border-b border-primary/15",
    tableRowAlt: "bg-accent/[0.02]",
    ptsBadge: "inline-flex items-center justify-center rounded-sm border border-accent/20 bg-accent/8 px-1.5 py-0.5 text-[11px] font-mono font-bold text-accent tabular-nums",
    timeslotHeader: "bg-primary text-primary-foreground flex items-center gap-2 px-3 py-1.5 border-b border-dashed border-primary",
    dateHeader: "bg-primary text-primary-foreground border border-primary px-2.5 py-0.5 rounded-sm text-[8px] font-mono font-bold uppercase tracking-[0.12em]",
    phaseTab: "px-2.5 py-1 rounded-sm text-[8px] font-mono font-bold uppercase tracking-[0.12em] whitespace-nowrap transition-all",
    phaseTabActive: "bg-accent text-accent-foreground",
    phaseTabInactive: "bg-card border border-primary/12 text-muted-foreground hover:text-primary hover:bg-primary/4",
    subHeader: "px-3 py-2 flex items-center justify-between gap-2 bg-primary/6 border-l border-dashed border-l-primary/40",
    subHeaderTitle: "font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-primary",
    subLabel: "inline-flex items-center px-2 py-0.5 font-mono text-[9px] font-bold uppercase tracking-[0.12em] text-accent",
  },

  // ── 7. LA GAZZETTA ───
  gazette: {
    sectionDot: "h-2.5 w-2.5 rounded-full bg-accent",
    sectionTitle: "text-xl font-black text-foreground italic leading-tight",
    sectionLine: "flex-1 border-b-2 border-double border-foreground/20",
    cardHeader: "bg-accent text-accent-foreground border-b-2 border-double border-accent px-3 py-2 flex items-center gap-2",
    cardHeaderDot: "h-2.5 w-2.5 rounded-full bg-accent-foreground",
    cardHeaderTitle: "text-[11px] font-bold text-accent-foreground italic uppercase",
    card: "border border-foreground/15 bg-card overflow-hidden",
    tabActive: "flex-1 px-2.5 py-1.5 text-[10px] font-bold italic transition-all bg-foreground text-background border-b-2 border-foreground",
    tabInactive: "flex-1 px-2.5 py-1.5 text-[10px] font-medium italic transition-all text-muted-foreground hover:text-foreground border-b-2 border-transparent hover:border-foreground/15",
    tabContainer: "flex bg-transparent p-0 border-b-2 border-double border-foreground/12",
    badge: "inline-flex items-center border border-accent/25 bg-accent/8 px-2 py-0.5 text-[9px] font-bold text-accent italic tabular-nums",
    label: "text-[9px] font-bold uppercase tracking-wide text-accent italic",
    backButton: "flex items-center gap-1 text-[11px] text-accent font-bold italic",
    matchContext: "bg-accent/10 px-3 py-1 border-b border-accent/15",
    matchContextText: "text-[9px] font-bold italic text-accent",
    matchTeamRowWin: "bg-accent/8",
    matchTeamName: "text-[11px] font-semibold truncate",
    matchTeamNameFav: "text-accent italic font-bold",
    matchScore: "text-xl font-black tabular-nums",
    matchScoreWin: "text-foreground",
    matchScoreLose: "text-muted-foreground",
    matchTimeBadge: "inline-flex items-center border border-foreground/15 bg-card px-2.5 py-0.5 text-[9px] font-bold text-foreground italic tabular-nums",
    matchFooter: "flex items-center justify-between px-3 py-1 bg-foreground/[0.03] border-t border-foreground/8",
    navBar: "bg-card border-t-2 border-double border-foreground/15",
    navCenter: "bg-accent text-accent-foreground border-accent rounded-full",
    navCenterActive: "bg-accent text-accent-foreground border-accent rounded-full scale-105",
    navTab: "text-muted-foreground hover:text-foreground",
    navTabActive: "text-accent",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-4 h-0.5 bg-accent rounded-full",
    tableHeader: "bg-accent/8 text-[9px] font-bold uppercase tracking-wide italic text-accent border-b border-accent/15",
    tableRowAlt: "bg-foreground/[0.02]",
    ptsBadge: "inline-flex items-center justify-center border border-foreground/20 bg-card px-1.5 py-0.5 text-[11px] font-bold text-foreground",
    timeslotHeader: "bg-foreground text-background flex items-center gap-2 px-3 py-1.5 border-b-2 border-double border-foreground",
    dateHeader: "bg-accent text-accent-foreground px-3 py-0.5 text-[9px] font-bold uppercase italic tracking-wider",
    phaseTab: "px-2.5 py-1 text-[9px] font-bold italic whitespace-nowrap transition-all",
    phaseTabActive: "bg-accent text-accent-foreground",
    phaseTabInactive: "bg-transparent border-b border-transparent text-muted-foreground hover:text-foreground hover:border-accent/25",
    subHeader: "px-3 py-2 flex items-center justify-between gap-2 bg-accent/8 border-b border-accent/20",
    subHeaderTitle: "text-[11px] font-bold italic uppercase text-foreground",
    subLabel: "inline-flex items-center px-2 py-0.5 text-[9px] font-bold italic uppercase tracking-wide text-accent",
  },

  // ── 8. SOCIAL MEDIA FEED ───
  social: {
    sectionDot: "hidden",
    sectionTitle: "text-sm font-semibold text-foreground",
    sectionLine: "flex-1 h-px bg-border/40",
    cardHeader: "bg-gradient-to-r from-primary to-accent text-white px-3 py-2 flex items-center gap-2 shadow-sm",
    cardHeaderDot: "h-1.5 w-1.5 rounded-full bg-white/90",
    cardHeaderTitle: "text-[11px] font-semibold text-white",
    card: "rounded-2xl border border-border/30 bg-card overflow-hidden shadow-[0_1px_10px_-3px_rgba(0,0,0,0.06)]",
    tabActive: "flex-1 px-2.5 py-2 rounded-xl text-[10px] font-semibold transition-all bg-gradient-to-r from-primary to-accent text-white shadow-sm",
    tabInactive: "flex-1 px-2.5 py-2 rounded-xl text-[10px] font-medium transition-all text-muted-foreground hover:text-foreground hover:bg-secondary/40",
    tabContainer: "flex rounded-2xl bg-secondary/40 p-0.5 gap-0.5",
    badge: "inline-flex items-center rounded-full bg-gradient-to-r from-primary/12 to-accent/12 border border-primary/15 px-2 py-0.5 text-[9px] font-semibold text-primary tabular-nums",
    label: "text-[9px] font-semibold text-accent",
    backButton: "flex items-center gap-1 text-[11px] text-primary font-semibold",
    matchContext: "px-3 py-1 bg-gradient-to-r from-primary/6 to-accent/6",
    matchContextText: "text-[9px] font-medium text-primary",
    matchTeamRowWin: "bg-gradient-to-r from-primary/4 to-accent/4",
    matchTeamName: "text-[11px] font-medium truncate",
    matchTeamNameFav: "text-accent font-semibold",
    matchScore: "text-xs font-bold tabular-nums",
    matchScoreWin: "text-primary",
    matchScoreLose: "text-muted-foreground",
    matchTimeBadge: "inline-flex items-center rounded-full bg-gradient-to-r from-primary/8 to-accent/8 border border-primary/12 px-2.5 py-0.5 text-[9px] font-semibold text-primary tabular-nums",
    matchFooter: "flex items-center justify-between px-3 py-1 border-t border-border/30",
    navBar: "bg-card/95 backdrop-blur-xl shadow-[0_-2px_20px_-4px_rgba(0,0,0,0.04)] border-t border-border/25",
    navCenter: "bg-gradient-to-br from-primary to-accent text-white border-transparent rounded-full shadow-sm",
    navCenterActive: "bg-gradient-to-br from-primary to-accent text-white border-transparent scale-105 shadow-md rounded-full",
    navTab: "text-muted-foreground hover:text-foreground",
    navTabActive: "text-primary",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-3.5 h-0.5 rounded-full bg-gradient-to-r from-primary to-accent",
    tableHeader: "text-[9px] font-semibold text-primary/60 border-b border-primary/12",
    tableRowAlt: "bg-secondary/15",
    ptsBadge: "inline-flex items-center justify-center rounded-full bg-gradient-to-r from-primary/12 to-accent/12 px-1.5 py-0.5 text-[11px] font-bold text-primary",
    timeslotHeader: "bg-gradient-to-r from-primary to-accent text-white flex items-center gap-2 px-3 py-1.5",
    dateHeader: "bg-gradient-to-r from-primary to-accent text-white px-3 py-0.5 rounded-full text-[9px] font-semibold shadow-sm",
    phaseTab: "px-2.5 py-1 rounded-xl text-[9px] font-semibold whitespace-nowrap transition-all",
    phaseTabActive: "bg-gradient-to-r from-primary to-accent text-white shadow-sm",
    phaseTabInactive: "bg-transparent text-muted-foreground hover:text-foreground hover:bg-secondary/40",
    subHeader: "px-3 py-2 flex items-center justify-between gap-2 bg-gradient-to-r from-primary/8 to-accent/8 rounded-xl",
    subHeaderTitle: "text-[10px] font-semibold uppercase tracking-wide text-foreground",
    subLabel: "inline-flex items-center px-2 py-0.5 text-[9px] font-semibold uppercase tracking-wide text-primary",
  },

  // ── 9. COPA MUNDO ─── premium European night-football: deep navy + electric blue
  copa_mundo: {
    sectionDot: "h-1.5 w-1.5 rounded-full bg-primary",
    sectionTitle: "text-[13px] font-extrabold italic text-foreground uppercase tracking-[0.14em]",
    sectionLine: "flex-1 h-px bg-gradient-to-r from-primary/25 to-transparent",
    cardHeader: "bg-accent text-accent-foreground border-b border-primary/20 px-3.5 py-2.5 flex items-center gap-2",
    cardHeaderDot: "h-1.5 w-1.5 rounded-full bg-primary",
    cardHeaderTitle: "text-[10px] font-extrabold italic text-accent-foreground uppercase tracking-[0.14em]",
    card: "rounded-2xl border border-primary/20 bg-card overflow-hidden",
    tabActive: "flex-1 px-3 py-2 text-[10px] font-extrabold italic uppercase tracking-[0.14em] transition-all text-primary border-b-2 border-primary",
    tabInactive: "flex-1 px-3 py-2 text-[10px] font-bold italic uppercase tracking-[0.14em] transition-all text-muted-foreground border-b-2 border-transparent hover:text-foreground",
    tabContainer: "flex gap-1 border-b border-primary/15",
    badge: "inline-flex items-center rounded-lg bg-secondary border border-primary/20 px-2 py-0.5 text-[9px] font-bold text-secondary-foreground tabular-nums",
    label: "text-[9px] font-extrabold italic uppercase tracking-[0.18em] text-primary",
    backButton: "flex items-center gap-1 text-[11px] text-primary font-extrabold uppercase tracking-[0.12em]",
    matchContext: "bg-secondary/60 px-3.5 py-1.5 border-b border-primary/15",
    matchContextText: "text-[9px] font-extrabold italic uppercase tracking-[0.14em] text-muted-foreground",
    matchTeamRowWin: "bg-primary/[0.06]",
    matchTeamName: "text-[11.5px] font-semibold truncate",
    matchTeamNameFav: "text-primary",
    matchScore: "text-[13px] font-extrabold tabular-nums",
    matchScoreWin: "text-primary",
    matchScoreLose: "text-muted-foreground",
    matchTimeBadge: "inline-flex items-center rounded-full bg-primary/15 border border-primary/30 px-2.5 py-0.5 text-[10px] font-extrabold text-primary tabular-nums",
    matchFooter: "flex items-center justify-between px-3.5 py-1.5 bg-secondary/40 border-t border-primary/15",
    navBar: "bg-background/95 backdrop-blur-xl border-t border-primary/20",
    navCenter: "bg-card text-muted-foreground border-primary/50 rounded-full shadow-[0_0_16px_-4px_hsl(var(--primary)/0.5)]",
    navCenterActive: "bg-card text-primary border-primary rounded-full scale-105 shadow-[0_0_20px_-3px_hsl(var(--primary)/0.65)]",
    navTab: "text-muted-foreground hover:text-foreground",
    navTabActive: "text-primary",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-4 h-0.5 rounded-full bg-primary",
    tableHeader: "bg-accent text-[9px] font-extrabold italic uppercase tracking-[0.12em] text-accent-foreground/70 border-b border-primary/20",
    tableRowAlt: "bg-primary/[0.04]",
    ptsBadge: "inline-flex items-center justify-center rounded-full bg-primary px-1.5 py-0.5 text-[11px] font-extrabold text-primary-foreground",
    timeslotHeader: "bg-accent text-accent-foreground flex items-center gap-2 px-3.5 py-2 border-b border-primary/20",
    dateHeader: "bg-primary/15 text-primary border border-primary/30 px-2.5 py-0.5 rounded-full text-[9px] font-extrabold italic uppercase tracking-[0.12em]",
    phaseTab: "px-3 py-1.5 rounded-full text-[9px] font-extrabold italic uppercase tracking-[0.12em] whitespace-nowrap transition-all",
    phaseTabActive: "bg-primary text-primary-foreground shadow-[0_0_14px_-4px_hsl(var(--primary)/0.7)]",
    phaseTabInactive: "bg-card border border-primary/20 text-muted-foreground hover:text-foreground hover:border-primary/50",
    subHeader: "px-3.5 py-2 flex items-center justify-between gap-2 bg-secondary/50 border-l-2 border-l-primary",
    subHeaderTitle: "text-[10px] font-extrabold italic uppercase tracking-[0.12em] text-foreground",
    subLabel: "inline-flex items-center px-2 py-0.5 text-[9px] font-extrabold uppercase tracking-[0.12em] text-primary",
  },

  // ── 10. NETFLIX ───
  netflix: {
    sectionDot: "h-1 w-5 rounded-sm bg-primary",
    sectionTitle: "text-base font-bold text-foreground uppercase tracking-wide",
    sectionLine: "flex-1 h-px bg-border/15",
    cardHeader: "bg-primary text-primary-foreground border-b border-primary px-3 py-2 flex items-center gap-2 shadow-md",
    cardHeaderDot: "h-1 w-4 rounded-sm bg-primary-foreground",
    cardHeaderTitle: "text-[10px] font-bold text-primary-foreground uppercase tracking-wider",
    card: "rounded-md border border-border/20 bg-card overflow-hidden shadow-md",
    tabActive: "flex-1 px-2.5 py-1.5 rounded-sm text-[10px] font-bold uppercase tracking-wider transition-all bg-primary text-primary-foreground",
    tabInactive: "flex-1 px-2.5 py-1.5 rounded-sm text-[10px] font-medium uppercase tracking-wider transition-all text-muted-foreground hover:text-foreground hover:bg-secondary/40",
    tabContainer: "flex rounded-md bg-secondary/15 p-0.5 gap-0.5",
    badge: "inline-flex items-center rounded bg-primary/12 border border-primary/20 px-2 py-0.5 text-[9px] font-bold text-primary tabular-nums",
    label: "text-[8px] font-bold uppercase tracking-[0.12em] text-primary",
    backButton: "flex items-center gap-1 text-[11px] text-primary font-bold uppercase tracking-wider",
    matchContext: "bg-primary/8 px-3 py-1 border-b border-primary/12",
    matchContextText: "text-[8px] font-bold uppercase tracking-[0.1em] text-primary",
    matchTeamRowWin: "bg-primary/6",
    matchTeamName: "text-[11px] font-semibold truncate",
    matchTeamNameFav: "text-primary",
    matchScore: "text-base font-bold tabular-nums",
    matchScoreWin: "text-foreground",
    matchScoreLose: "text-muted-foreground/50",
    matchTimeBadge: "inline-flex items-center rounded bg-accent/12 border border-accent/15 px-2.5 py-0.5 text-[9px] font-bold text-accent tabular-nums",
    matchFooter: "flex items-center justify-between px-3 py-1 bg-accent/4 border-t border-accent/8",
    navBar: "bg-card border-t border-primary/25",
    navCenter: "bg-primary text-primary-foreground border-primary rounded-md",
    navCenterActive: "bg-primary text-primary-foreground border-primary scale-105 shadow-md rounded-md",
    navTab: "text-muted-foreground hover:text-foreground",
    navTabActive: "text-primary",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-4 h-0.5 bg-primary rounded-full",
    tableHeader: "bg-primary/6 text-[9px] font-bold uppercase tracking-wider text-accent border-b border-primary/12",
    tableRowAlt: "bg-accent/[0.02]",
    ptsBadge: "inline-flex items-center justify-center rounded bg-primary text-primary-foreground px-1.5 py-0.5 text-[11px] font-bold",
    timeslotHeader: "bg-primary text-primary-foreground flex items-center gap-2 px-3 py-1.5 border-b border-primary",
    dateHeader: "bg-primary text-primary-foreground px-2.5 py-0.5 rounded text-[9px] font-bold uppercase tracking-wider",
    phaseTab: "px-2.5 py-1 rounded-sm text-[9px] font-bold uppercase tracking-wider whitespace-nowrap transition-all",
    phaseTabActive: "bg-primary text-primary-foreground",
    phaseTabInactive: "bg-card border border-border/20 text-muted-foreground hover:text-foreground hover:bg-primary/4",
    subHeader: "px-3 py-2 flex items-center justify-between gap-2 bg-foreground/[0.03] border-l-3 border-l-primary",
    subHeaderTitle: "text-[10px] font-black uppercase tracking-wider text-foreground",
    subLabel: "inline-flex items-center px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider text-primary",
  },

  // ── 11. WORLD CUP 2026 ───
  world_cup: {
    sectionDot: "h-2.5 w-2.5 rounded-full bg-[#5BE7D6] ring-2 ring-[#5BE7D6]/30",
    sectionTitle: "text-base font-black text-[#1FB8A8] uppercase tracking-[0.06em] italic",
    sectionLine: "flex-1 h-0.5 bg-[#5BE7D6]/40 rounded-full",
    cardHeader: "bg-foreground text-background px-4 py-2.5 flex items-center gap-2 rounded-t-2xl shadow-[0_4px_16px_-4px_rgba(0,0,0,0.3)]",
    cardHeaderDot: "h-2 w-2 rounded-full bg-[#5BE7D6]",
    cardHeaderTitle: "text-[11px] font-black text-background uppercase tracking-[0.14em] italic",
    card: "rounded-2xl border border-[#5BE7D6]/30 bg-card overflow-hidden shadow-[0_2px_12px_-4px_rgba(91,231,214,0.35)]",
    tabActive: "flex-1 px-2.5 py-1.5 rounded-full text-[10px] font-black uppercase tracking-[0.1em] italic transition-all bg-[#5BE7D6] text-black shadow-sm",
    tabInactive: "flex-1 px-2.5 py-1.5 rounded-full text-[10px] font-bold uppercase tracking-[0.1em] italic transition-all text-muted-foreground hover:text-foreground",
    tabContainer: "flex rounded-full bg-secondary/40 p-0.5 gap-0.5 ring-1 ring-[#5BE7D6]/20",
    badge: "inline-flex items-center rounded-full bg-[#5BE7D6] text-black px-2 py-0.5 text-[9px] font-black uppercase tabular-nums tracking-wide",
    label: "text-[9px] font-black uppercase tracking-[0.14em] text-[#1FB8A8] italic",
    backButton: "flex items-center gap-1 text-[11px] text-foreground font-black uppercase tracking-[0.1em] italic",
    matchContext: "bg-foreground text-background px-3 py-1 rounded-t-xl",
    matchContextText: "text-[9px] font-black uppercase tracking-[0.14em] text-background italic",
    matchTeamRowWin: "bg-[#5BE7D6]/15 rounded-lg",
    matchTeamName: "text-[11px] font-black truncate uppercase italic tracking-tight",
    matchTeamNameFav: "text-[#1FB8A8]",
    matchScore: "text-base font-black tabular-nums italic px-2 rounded-md bg-[#5BE7D6] text-black",
    matchScoreWin: "text-black",
    matchScoreLose: "text-black/60",
    matchTimeBadge: "inline-flex items-center rounded-full bg-[#5BE7D6] text-black px-2.5 py-0.5 text-[9px] font-black tabular-nums tracking-wider italic",
    matchFooter: "flex items-center justify-between px-3 py-1 bg-[#5BE7D6]/10 border-t border-[#5BE7D6]/30",
    navBar: "bg-card/98 backdrop-blur-xl border-t-2 border-[#5BE7D6]/30 shadow-[0_-2px_16px_-4px_rgba(91,231,214,0.25)]",
    navCenter: "bg-[#5BE7D6] text-black border-[#5BE7D6] rounded-full ring-2 ring-[#5BE7D6]/40",
    navCenterActive: "bg-[#5BE7D6] text-black border-[#5BE7D6] scale-110 shadow-lg rounded-full ring-2 ring-[#5BE7D6]",
    navTab: "text-muted-foreground hover:text-foreground",
    navTabActive: "text-[#1FB8A8]",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-2 h-2 rounded-full bg-[#5BE7D6]",
    tableHeader: "bg-foreground text-background text-[9px] font-black uppercase tracking-[0.12em] italic",
    tableRowAlt: "bg-[#5BE7D6]/[0.06]",
    ptsBadge: "inline-flex items-center justify-center rounded-full bg-[#5BE7D6] text-black px-2 py-0.5 text-[11px] font-black tabular-nums",
    timeslotHeader: "bg-foreground text-background flex items-center gap-2 px-4 py-2 rounded-t-2xl italic shadow-[0_4px_16px_-4px_rgba(0,0,0,0.3)]",
    dateHeader: "bg-[#5BE7D6] text-black px-3 py-0.5 rounded-full text-[9px] font-black uppercase tracking-[0.12em] italic ring-1 ring-[#5BE7D6]/40",
    phaseTab: "px-3 py-1 rounded-full text-[9px] font-black uppercase tracking-[0.1em] italic whitespace-nowrap transition-all",
    phaseTabActive: "bg-[#5BE7D6] text-black shadow-sm",
    phaseTabInactive: "bg-card border border-[#5BE7D6]/30 text-muted-foreground hover:text-foreground hover:border-[#5BE7D6]/60",
    subHeader: "px-4 py-2 flex items-center justify-between gap-2 bg-[#5BE7D6] text-black italic",
    subHeaderTitle: "text-[11px] font-black uppercase tracking-[0.14em] text-black italic",
    subLabel: "text-[10px] font-black uppercase tracking-[0.18em] text-black italic",
  },

  // ── 12. WORLD CUP — MEXICO (green Trionda) ───
  // Identiek aan world_cup base; enkel TITELBALKEN krijgen Mexico-groen met chevron-motief.
  world_cup_mexico: {
    sectionDot: "h-2.5 w-2.5 rounded-full wc-mx-solid ring-2 ring-white/10",
    sectionTitle: "text-base font-black text-foreground uppercase tracking-[0.06em] italic",
    sectionLine: "flex-1 h-0.5 bg-foreground/15 rounded-full",
    sectionMeta: "text-[10px] font-bold uppercase text-foreground",
    cardHeader: "wc-mx-bg text-white px-4 py-2.5 flex items-center gap-2 rounded-t-2xl shadow-[0_4px_16px_-4px_rgba(0,104,63,0.4)] [&_svg]:text-white [&_svg]:stroke-white [&_svg]:stroke-[2.5]",
    cardHeaderDot: "h-2 w-2 rounded-full bg-white",
    cardHeaderTitle: "text-[12px] font-black text-white uppercase tracking-[0.14em] italic",
    homeCardHeader: "wc-mx-bg text-white px-4 py-2.5 flex items-center gap-2 rounded-t-2xl shadow-[0_4px_16px_-4px_rgba(0,104,63,0.4)] [&_svg]:text-white [&_svg]:stroke-white [&_svg]:stroke-[2.5]",
    homeCardHeaderDot: "h-2 w-2 rounded-full bg-white",
    homeCardHeaderTitle: "text-[12px] font-black text-white uppercase tracking-[0.14em] italic",
    card: "rounded-2xl border border-foreground/10 bg-card overflow-hidden shadow-[0_2px_12px_-4px_hsl(var(--primary)/0.25)]",
    tabActive: "flex-1 px-2.5 py-1.5 rounded-full text-[10px] font-black uppercase tracking-[0.1em] italic transition-all bg-foreground text-background shadow-sm",
    tabInactive: "flex-1 px-2.5 py-1.5 rounded-full text-[10px] font-bold uppercase tracking-[0.1em] italic transition-all text-muted-foreground hover:text-foreground",
    tabContainer: "flex rounded-full bg-secondary/40 p-0.5 gap-0.5 ring-1 ring-foreground/10",
    badge: "inline-flex items-center rounded-full wc-mx-solid text-white px-2 py-0.5 text-[9px] font-black uppercase tabular-nums tracking-wide",
    label: "text-[9px] font-black uppercase tracking-[0.14em] text-primary italic",
    backButton: "flex items-center gap-1 text-[11px] text-foreground font-black uppercase tracking-[0.1em] italic",
    matchContext: "bg-foreground text-background px-3 py-1 rounded-t-xl",
    matchContextText: "text-[9px] font-black uppercase tracking-[0.14em] text-background italic",
    matchTeamRowWin: "bg-primary/10 rounded-lg",
    matchTeamName: "text-[11px] font-black truncate uppercase italic tracking-tight",
    matchTeamNameFav: "text-primary",
    matchScore: "text-base font-black tabular-nums italic",
    matchScoreWin: "text-foreground",
    matchScoreLose: "text-muted-foreground",
    matchTimeBadge: "inline-flex items-center rounded-full wc-mx-solid text-white px-2.5 py-0.5 text-[9px] font-black tabular-nums tracking-wider italic",
    matchFooter: "flex items-center justify-between px-3 py-1 bg-primary/6 border-t border-primary/12",
    navBar: "bg-card/98 backdrop-blur-xl border-t-2 border-foreground/10 shadow-[0_-2px_16px_-4px_hsl(var(--primary)/0.15)]",
    navCenter: "bg-foreground text-background border-foreground rounded-full ring-2 ring-accent/40",
    navCenterActive: "wc-mx-solid text-white border-transparent scale-110 shadow-lg rounded-full ring-2 ring-white/40",
    navTab: "text-muted-foreground hover:text-foreground",
    navTabActive: "text-[#00683F]",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-2 h-2 rounded-full wc-mx-solid",
    tableHeader: "bg-foreground text-background text-[9px] font-black uppercase tracking-[0.12em] italic",
    tableRowAlt: "bg-primary/[0.04]",
    ptsBadge: "inline-flex items-center justify-center rounded-full wc-mx-solid text-white px-2 py-0.5 text-[11px] font-black tabular-nums",
    timeslotHeader: "wc-mx-bg text-white flex items-center gap-2 px-4 py-2 rounded-t-2xl italic shadow-[0_4px_16px_-4px_rgba(0,104,63,0.4)] [&_svg]:text-white [&_svg]:stroke-white [&_svg]:stroke-[2.5]",
    timeslotHeaderMeta: "text-[12px] font-black text-white uppercase tracking-[0.14em] italic",
    dateHeader: "wc-mx-solid text-white px-3 py-0.5 rounded-full text-[12px] font-black uppercase tracking-[0.14em] italic shadow-sm",
    phaseTab: "px-3 py-1 rounded-full text-[12px] font-black uppercase tracking-[0.14em] italic whitespace-nowrap transition-all",
    phaseTabActive: "bg-foreground text-background shadow-sm",
    phaseTabInactive: "bg-card border border-foreground/15 text-muted-foreground hover:text-foreground hover:border-foreground/30",
    subHeader: "px-4 py-2 flex items-center justify-between gap-2 wc-mx-bg text-white italic [&_svg]:text-white [&_svg]:stroke-white [&_svg]:stroke-[2.5]",
    subHeaderTitle: "text-[12px] font-black uppercase tracking-[0.14em] text-white italic",
    subLabel: "text-[12px] font-black uppercase tracking-[0.14em] text-white italic",
  },

  // ── 13. WORLD CUP — CANADA (red Trionda) ───
  world_cup_canada: {
    sectionDot: "h-2.5 w-2.5 rounded-full wc-ca-solid ring-2 ring-white/10",
    sectionTitle: "text-base font-black text-foreground uppercase tracking-[0.06em] italic",
    sectionLine: "flex-1 h-0.5 bg-foreground/15 rounded-full",
    sectionMeta: "text-[10px] font-bold uppercase text-foreground",
    cardHeader: "wc-ca-bg text-white px-4 py-2.5 flex items-center gap-2 rounded-t-2xl shadow-[0_4px_16px_-4px_rgba(139,0,0,0.4)]",
    cardHeaderDot: "h-2 w-2 rounded-full bg-white/95",
    cardHeaderTitle: "text-[11px] font-black text-white uppercase tracking-[0.14em] italic [text-shadow:0_1px_2px_rgba(0,0,0,0.35)]",
    homeCardHeader: "wc-ca-bg text-white px-4 py-2.5 flex items-center gap-2 rounded-t-2xl shadow-[0_4px_16px_-4px_rgba(139,0,0,0.4)]",
    homeCardHeaderDot: "h-2 w-2 rounded-full bg-white/95",
    homeCardHeaderTitle: "text-[11px] font-black text-white uppercase tracking-[0.14em] italic [text-shadow:0_1px_2px_rgba(0,0,0,0.35)]",
    card: "rounded-2xl border border-foreground/10 bg-card overflow-hidden shadow-[0_2px_12px_-4px_hsl(var(--primary)/0.25)]",
    tabActive: "flex-1 px-2.5 py-1.5 rounded-full text-[10px] font-black uppercase tracking-[0.1em] italic transition-all bg-foreground text-background shadow-sm",
    tabInactive: "flex-1 px-2.5 py-1.5 rounded-full text-[10px] font-bold uppercase tracking-[0.1em] italic transition-all text-muted-foreground hover:text-foreground",
    tabContainer: "flex rounded-full bg-secondary/40 p-0.5 gap-0.5 ring-1 ring-foreground/10",
    badge: "inline-flex items-center rounded-full wc-ca-solid text-white px-2 py-0.5 text-[9px] font-black uppercase tabular-nums tracking-wide",
    label: "text-[9px] font-black uppercase tracking-[0.14em] text-primary italic",
    backButton: "flex items-center gap-1 text-[11px] text-foreground font-black uppercase tracking-[0.1em] italic",
    matchContext: "bg-foreground text-background px-3 py-1 rounded-t-xl",
    matchContextText: "text-[9px] font-black uppercase tracking-[0.14em] text-background italic",
    matchTeamRowWin: "bg-primary/10 rounded-lg",
    matchTeamName: "text-[11px] font-black truncate uppercase italic tracking-tight",
    matchTeamNameFav: "text-primary",
    matchScore: "text-base font-black tabular-nums italic",
    matchScoreWin: "text-foreground",
    matchScoreLose: "text-muted-foreground",
    matchTimeBadge: "inline-flex items-center rounded-full wc-ca-solid text-white px-2.5 py-0.5 text-[9px] font-black tabular-nums tracking-wider italic",
    matchFooter: "flex items-center justify-between px-3 py-1 bg-primary/6 border-t border-primary/12",
    navBar: "bg-card/98 backdrop-blur-xl border-t-2 border-foreground/10 shadow-[0_-2px_16px_-4px_hsl(var(--primary)/0.15)]",
    navCenter: "bg-foreground text-background border-foreground rounded-full ring-2 ring-accent/40",
    navCenterActive: "wc-ca-solid text-white border-transparent scale-110 shadow-lg rounded-full ring-2 ring-white/40",
    navTab: "text-muted-foreground hover:text-foreground",
    navTabActive: "text-[#8B0000]",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-2 h-2 rounded-full wc-ca-solid",
    tableHeader: "bg-foreground text-background text-[9px] font-black uppercase tracking-[0.12em] italic",
    tableRowAlt: "bg-primary/[0.04]",
    ptsBadge: "inline-flex items-center justify-center rounded-full wc-ca-solid text-white px-2 py-0.5 text-[11px] font-black tabular-nums",
    timeslotHeader: "wc-ca-bg text-white flex items-center gap-2 px-4 py-2 rounded-t-2xl italic shadow-[0_4px_16px_-4px_rgba(139,0,0,0.4)]",
    timeslotHeaderMeta: "text-[10px] font-bold text-white/90 uppercase tracking-wider",
    dateHeader: "wc-ca-solid text-white px-3 py-0.5 rounded-full text-[9px] font-black uppercase tracking-[0.12em] italic shadow-sm",
    phaseTab: "px-3 py-1 rounded-full text-[9px] font-black uppercase tracking-[0.1em] italic whitespace-nowrap transition-all",
    phaseTabActive: "bg-foreground text-background shadow-sm",
    phaseTabInactive: "bg-card border border-foreground/15 text-muted-foreground hover:text-foreground hover:border-foreground/30",
    subHeader: "px-4 py-2 flex items-center justify-between gap-2 wc-ca-bg text-white italic",
    subHeaderTitle: "text-[11px] font-black uppercase tracking-[0.14em] text-white italic [text-shadow:0_1px_2px_rgba(0,0,0,0.35)]",
    subLabel: "text-[10px] font-black uppercase tracking-[0.18em] text-white/85 italic",
  },

  // ── 14. WORLD CUP — USA (blue Trionda stars) ───
  world_cup_usa: {
    sectionDot: "h-2.5 w-2.5 rounded-full wc-us-solid ring-2 ring-white/10",
    sectionTitle: "text-base font-black text-foreground uppercase tracking-[0.06em] italic",
    sectionLine: "flex-1 h-0.5 bg-foreground/15 rounded-full",
    sectionMeta: "text-[10px] font-bold uppercase text-foreground",
    cardHeader: "wc-us-bg text-white px-4 py-2.5 flex items-center gap-2 rounded-t-2xl shadow-[0_4px_16px_-4px_rgba(26,63,168,0.4)]",
    cardHeaderDot: "h-2 w-2 rounded-full bg-white/95",
    cardHeaderTitle: "text-[11px] font-black text-white uppercase tracking-[0.14em] italic [text-shadow:0_1px_2px_rgba(0,0,0,0.35)]",
    homeCardHeader: "wc-us-bg text-white px-4 py-2.5 flex items-center gap-2 rounded-t-2xl shadow-[0_4px_16px_-4px_rgba(26,63,168,0.4)]",
    homeCardHeaderDot: "h-2 w-2 rounded-full bg-white/95",
    homeCardHeaderTitle: "text-[11px] font-black text-white uppercase tracking-[0.14em] italic [text-shadow:0_1px_2px_rgba(0,0,0,0.35)]",
    card: "rounded-2xl border border-foreground/10 bg-card overflow-hidden shadow-[0_2px_12px_-4px_hsl(var(--primary)/0.25)]",
    tabActive: "flex-1 px-2.5 py-1.5 rounded-full text-[10px] font-black uppercase tracking-[0.1em] italic transition-all bg-foreground text-background shadow-sm",
    tabInactive: "flex-1 px-2.5 py-1.5 rounded-full text-[10px] font-bold uppercase tracking-[0.1em] italic transition-all text-muted-foreground hover:text-foreground",
    tabContainer: "flex rounded-full bg-secondary/40 p-0.5 gap-0.5 ring-1 ring-foreground/10",
    badge: "inline-flex items-center rounded-full wc-us-solid text-white px-2 py-0.5 text-[9px] font-black uppercase tabular-nums tracking-wide",
    label: "text-[9px] font-black uppercase tracking-[0.14em] text-primary italic",
    backButton: "flex items-center gap-1 text-[11px] text-foreground font-black uppercase tracking-[0.1em] italic",
    matchContext: "bg-foreground text-background px-3 py-1 rounded-t-xl",
    matchContextText: "text-[9px] font-black uppercase tracking-[0.14em] text-background italic",
    matchTeamRowWin: "bg-primary/10 rounded-lg",
    matchTeamName: "text-[11px] font-black truncate uppercase italic tracking-tight",
    matchTeamNameFav: "text-primary",
    matchScore: "text-base font-black tabular-nums italic",
    matchScoreWin: "text-foreground",
    matchScoreLose: "text-muted-foreground",
    matchTimeBadge: "inline-flex items-center rounded-full wc-us-solid text-white px-2.5 py-0.5 text-[9px] font-black tabular-nums tracking-wider italic",
    matchFooter: "flex items-center justify-between px-3 py-1 bg-primary/6 border-t border-primary/12",
    navBar: "bg-card/98 backdrop-blur-xl border-t-2 border-foreground/10 shadow-[0_-2px_16px_-4px_hsl(var(--primary)/0.15)]",
    navCenter: "bg-foreground text-background border-foreground rounded-full ring-2 ring-accent/40",
    navCenterActive: "wc-us-solid text-white border-transparent scale-110 shadow-lg rounded-full ring-2 ring-white/40",
    navTab: "text-muted-foreground hover:text-foreground",
    navTabActive: "text-[#1A3FA8]",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-2 h-2 rounded-full wc-us-solid",
    tableHeader: "bg-foreground text-background text-[9px] font-black uppercase tracking-[0.12em] italic",
    tableRowAlt: "bg-primary/[0.04]",
    ptsBadge: "inline-flex items-center justify-center rounded-full wc-us-solid text-white px-2 py-0.5 text-[11px] font-black tabular-nums",
    timeslotHeader: "wc-us-bg text-white flex items-center gap-2 px-4 py-2 rounded-t-2xl italic shadow-[0_4px_16px_-4px_rgba(26,63,168,0.4)]",
    timeslotHeaderMeta: "text-[10px] font-bold text-white/90 uppercase tracking-wider",
    dateHeader: "wc-us-solid text-white px-3 py-0.5 rounded-full text-[9px] font-black uppercase tracking-[0.12em] italic shadow-sm",
    phaseTab: "px-3 py-1 rounded-full text-[9px] font-black uppercase tracking-[0.1em] italic whitespace-nowrap transition-all",
    phaseTabActive: "bg-foreground text-background shadow-sm",
    phaseTabInactive: "bg-card border border-foreground/15 text-muted-foreground hover:text-foreground hover:border-foreground/30",
    subHeader: "px-4 py-2 flex items-center justify-between gap-2 wc-us-bg text-white italic",
    subHeaderTitle: "text-[11px] font-black uppercase tracking-[0.14em] text-white italic [text-shadow:0_1px_2px_rgba(0,0,0,0.35)]",
    subLabel: "text-[10px] font-black uppercase tracking-[0.18em] text-white/85 italic",
  },

  // ── 15. RETRO FOOTBALL ─── 1978 matchday programme: cream paper, forest green, faded red
  retro_football: {
    sectionDot: "h-3 w-1 bg-primary",
    sectionTitle: "font-['Roboto_Condensed'] text-[15px] font-extrabold text-accent uppercase tracking-[0.06em]",
    sectionLine: "flex-1 h-px bg-border/70",
    cardHeader: "bg-accent text-accent-foreground border-b-2 border-accent px-3 py-2 flex items-center gap-2",
    cardHeaderDot: "h-2.5 w-0.5 bg-primary",
    cardHeaderTitle: "font-['Roboto_Condensed'] text-[11px] font-extrabold text-accent-foreground uppercase tracking-[0.08em]",
    card: "rounded-[4px] border border-border bg-card overflow-hidden",
    tabActive: "flex-1 px-3 py-2 font-['Roboto_Condensed'] text-[11px] font-extrabold uppercase tracking-[0.08em] transition-all text-primary border-b-2 border-primary",
    tabInactive: "flex-1 px-3 py-2 font-['Roboto_Condensed'] text-[11px] font-bold uppercase tracking-[0.08em] transition-all text-muted-foreground border-b-2 border-transparent hover:text-accent",
    tabContainer: "flex gap-2 border-b border-border",
    badge: "inline-flex items-center rounded-[3px] border border-border bg-secondary px-2 py-0.5 font-['Roboto_Condensed'] text-[10px] font-bold text-secondary-foreground tabular-nums uppercase",
    label: "font-['Roboto_Condensed'] text-[10px] font-extrabold uppercase tracking-[0.12em] text-primary",
    backButton: "flex items-center gap-1 font-['Roboto_Condensed'] text-[12px] text-primary font-extrabold uppercase tracking-[0.08em]",
    matchContext: "bg-secondary px-3 py-1 border-b border-border",
    matchContextText: "font-['Roboto_Condensed'] text-[10px] font-extrabold uppercase tracking-[0.08em] text-accent",
    matchTeamRow: "rounded-[3px]",
    matchTeamRowWin: "bg-primary/[0.08]",
    matchTeamName: "text-[11.5px] font-semibold truncate uppercase",
    matchTeamNameFav: "text-primary",
    matchScore: "font-['Roboto_Condensed'] text-[15px] font-extrabold tabular-nums",
    matchScoreWin: "text-primary",
    matchScoreLose: "text-muted-foreground",
    matchTimeBadge: "inline-flex items-center rounded-[3px] bg-primary text-primary-foreground px-2 py-0.5 font-['Roboto_Condensed'] text-[11px] font-extrabold tabular-nums",
    matchFooter: "flex items-center justify-between px-3 py-1 bg-secondary/60 border-t border-border",
    matchCardWrapper: "rounded-[4px] border border-border bg-card overflow-hidden",
    navBar: "bg-background border-t-2 border-accent",
    navCenter: "bg-accent text-accent-foreground border-background rounded-full ring-1 ring-primary",
    navCenterActive: "bg-accent text-primary-foreground border-background rounded-full ring-1 ring-primary scale-105",
    navTab: "text-foreground/70 hover:text-accent",
    navTabActive: "text-primary",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-4 h-0.5 bg-primary",
    tableHeader: "bg-accent text-accent-foreground font-['Roboto_Condensed'] text-[10px] font-extrabold uppercase tracking-[0.08em] border-b border-accent",
    tableRowAlt: "bg-secondary/40",
    ptsBadge: "inline-flex items-center justify-center rounded-[3px] bg-primary text-primary-foreground px-1.5 py-0.5 font-['Roboto_Condensed'] text-[12px] font-extrabold tabular-nums",
    timeslotHeader: "bg-accent text-accent-foreground flex items-center gap-2 px-3 py-1.5 border-b-2 border-accent",
    timeslotBadge: "inline-flex items-center rounded-[3px] border border-accent-foreground/40 px-2 py-0.5 font-['Roboto_Condensed'] text-[10px] font-extrabold text-accent-foreground tabular-nums",
    timeslotHeaderMeta: "font-['Roboto_Condensed'] text-[11px] font-bold text-accent-foreground/85 uppercase tracking-[0.06em]",
    dateHeader: "bg-primary text-primary-foreground px-2 py-0.5 rounded-[3px] font-['Roboto_Condensed'] text-[10px] font-extrabold uppercase tracking-[0.08em]",
    phaseTab: "px-2.5 py-1 rounded-[3px] font-['Roboto_Condensed'] text-[10px] font-extrabold uppercase tracking-[0.08em] whitespace-nowrap transition-all",
    phaseTabActive: "bg-primary text-primary-foreground border border-primary",
    phaseTabInactive: "bg-card border border-accent/60 text-accent hover:border-primary",
    subHeader: "px-3 py-1.5 flex items-center justify-between gap-2 bg-accent text-accent-foreground",
    subHeaderTitle: "font-['Roboto_Condensed'] text-[11px] font-extrabold uppercase tracking-[0.08em] text-accent-foreground",
    subLabel: "inline-flex items-center px-2 py-0.5 font-['Roboto_Condensed'] text-[10px] font-extrabold uppercase tracking-[0.08em] text-accent-foreground/85",
  },
  // ── BROADCAST #1: COPA MUNDO (new generation) ───
  copa_mundo_bc: {
    sectionDot: "h-3.5 w-1 rounded-full bg-primary",
    sectionTitle: "text-[15px] font-bold text-foreground tracking-tight",
    sectionMeta: "text-[11px] font-medium text-muted-foreground",
    sectionLine: "flex-1 h-px bg-border",
    card: "rounded-[10px] border border-border bg-card overflow-hidden",
    matchCardWrapper: "rounded-[10px] border border-border bg-card overflow-hidden",
    cardHeader: "bg-secondary border-b border-border px-3 py-2 flex items-center gap-2",
    cardHeaderDot: "h-1.5 w-1.5 rounded-full bg-primary",
    cardHeaderTitle: "text-[10px] font-semibold text-foreground uppercase tracking-[0.08em]",
    homeCardHeader: "bg-secondary border-b border-border px-3 py-2 flex items-center gap-2",
    homeCardHeaderTitle: "text-[11px] font-semibold text-foreground uppercase tracking-[0.08em]",
    tabContainer: "flex gap-1 rounded-[8px] bg-secondary border border-border p-1",
    tabActive: "flex-1 px-3 py-1.5 rounded-[6px] text-[11px] font-semibold transition-colors bg-primary text-primary-foreground",
    tabInactive: "flex-1 px-3 py-1.5 rounded-[6px] text-[11px] font-medium transition-colors text-muted-foreground hover:text-foreground",
    badge: "inline-flex items-center rounded-[6px] bg-secondary border border-border px-2 py-0.5 text-[10px] font-semibold text-foreground tabular-nums",
    label: "text-[10px] font-semibold uppercase tracking-[0.08em] text-muted-foreground",
    backButton: "flex items-center gap-1 text-[11px] font-semibold text-primary",
    matchContext: "bg-secondary px-3 py-1.5 border-b border-border",
    matchContextText: "text-[10px] font-semibold uppercase tracking-[0.08em] text-muted-foreground",
    matchTeamRow: "px-3 py-2",
    matchTeamRowWin: "bg-primary/[0.07]",
    matchTeamName: "text-[12px] font-semibold truncate",
    matchTeamNameFav: "text-primary",
    matchScore: "text-[14px] font-extrabold tabular-nums",
    matchScoreWin: "text-foreground",
    matchScoreLose: "text-muted-foreground",
    matchTimeBadge: "inline-flex items-center rounded-[6px] border border-primary/40 bg-primary/10 px-2 py-0.5 text-[11px] font-bold text-primary tabular-nums",
    matchFooter: "flex items-center justify-between px-3 py-1.5 bg-secondary/60 border-t border-border",
    navBar: "bg-background/95 backdrop-blur-md border-t border-border",
    navCenter: "bg-card text-muted-foreground border-border rounded-full",
    navCenterActive: "bg-card text-primary border-primary rounded-full scale-105",
    navTab: "text-muted-foreground hover:text-foreground",
    navTabActive: "text-primary",
    navIndicator: "absolute -bottom-1 left-1/2 -translate-x-1/2 w-4 h-0.5 rounded-full bg-primary",
    tableHeader: "bg-secondary text-[10px] font-semibold uppercase tracking-[0.06em] text-muted-foreground border-b border-border",
    tableRowAlt: "bg-secondary/40",
    ptsBadge: "inline-flex items-center justify-center rounded-[6px] bg-primary px-1.5 py-0.5 text-[11px] font-extrabold text-primary-foreground tabular-nums",
    timeslotHeader: "bg-secondary text-foreground flex items-center gap-2 px-3 py-2 border-b border-border",
    timeslotBadge: "inline-flex items-center rounded-[6px] border border-primary/40 bg-primary/10 px-2 py-0.5 text-[11px] font-bold text-primary tabular-nums",
    timeslotHeaderMeta: "text-[11px] font-medium text-muted-foreground",
    dateHeader: "bg-primary text-primary-foreground px-2.5 py-0.5 rounded-[6px] text-[10px] font-semibold uppercase tracking-[0.06em]",
    phaseTab: "px-3 py-1.5 rounded-[8px] text-[10px] font-semibold uppercase tracking-[0.06em] whitespace-nowrap transition-colors",
    phaseTabActive: "bg-primary text-primary-foreground",
    phaseTabInactive: "bg-card border border-border text-muted-foreground hover:text-foreground hover:border-primary/40",
    subHeader: "px-3 py-2 flex items-center justify-between gap-2 bg-secondary border-l-2 border-l-primary",
    subHeaderTitle: "text-[11px] font-bold uppercase tracking-[0.06em] text-foreground",
    subLabel: "inline-flex items-center px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.06em] text-muted-foreground",
  },
};


/** Nieuwe generatie broadcast styles (light + dark via semantische tokens). */
export const BROADCAST_GENERATION: Record<BroadcastStyle, "broadcast" | "legacy"> = Object.fromEntries(
  (Object.keys(BROADCAST_STYLES) as BroadcastStyle[]).map((k) => [k, k === "copa_mundo_bc" ? "broadcast" : "legacy"])
) as Record<BroadcastStyle, "broadcast" | "legacy">;

export const NEW_BROADCAST_STYLES: BroadcastStyle[] = ["copa_mundo_bc"];


export function ds(style: BroadcastStyle, token: string): string {
  return STYLES[style]?.[token] ?? "";
}
